receivers:
  otlp:
    protocols:
      grpc: # port 4317

      http: # port 4318

processors:
  batch:

exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "cHPLvVrtRYjMqNcVwkAauD"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]